set_property -dict { PACKAGE_PIN V10   IOSTANDARD LVCMOS33 } [get_ports { write }];
set_property -dict { PACKAGE_PIN E3   IOSTANDARD LVCMOS33 } [get_ports { clk}];
set_property -dict { PACKAGE_PIN U11   IOSTANDARD LVCMOS33 } [get_ports { reset}];
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {a[1]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {a[0]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {b[1]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {b[0]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {S[0]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {S[1]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {S[2]}]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports ae]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports be]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports c]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports d]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports e]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports f]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports g]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports DP]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {AN[0]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {AN[1]}]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {AN[2]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {AN[3]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {AN[4]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {AN[5]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {AN[6]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {AN[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {clk[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {write[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {write[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {write[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clock_div]
